let div1=document.createElement('div');
            div1.classList.add('div1');
            document.body.appendChild(div1);
            let count=10;
            setTimeout(function(){
                div1.innerText=count;
                setTimeout(function(){
                    count--;
                    div1.innerText=count;
                    setTimeout(function(){
                        count--;
                        div1.innerText=count;
                        setTimeout(function(){
                            count--;
                            div1.innerText=count;
                            setTimeout(function(){
                                count--;
                                div1.innerText=count;
                                setTimeout(function(){
                                    count--;
                                    div1.innerText=count;
                                    setTimeout(function(){
                                        count--;
                                        div1.innerText=count;
                                        setTimeout(function(){
                                            count--;
                                            div1.innerText=count;
                                            setTimeout(function(){
                                                count--;
                                                div1.innerText=count;
                                                setTimeout(function(){
                                                    count--;
                                                    div1.innerText=count;
                                                    setTimeout(function(){
                                                        count--;
                                                        div1.innerText='Happy New Year';
                                                        let img=document.createElement('img');
                                                        img.src="https://as2.ftcdn.net/jpg/03/73/88/59/500_F_373885907_TpLabK3QbPjfwYvPTXDIm5vrYbgTJIJd.jpg"
                                                        div1.appendChild(img);
                                                    },1000);
                                                },1000);
                                            },1000);
                                        },1000);
                                    },1000);
                                },1000); 
                            },1000);
                        },1000);
                    },1000);
                },1000);
            },1000);